version: '2'

services:
  web4:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=/usr/src/microblog.py
      - FLASK_DEBUG=1
    volumes:
      - .:/usr/src/
    command: flask run --host=0.0.0.0 --port=5001
    depends_on:
      - postgres

  postgres:
    restart: always
    build: Postgresql
    volumes:
      - /Users/lukasz/docker_volumes/postgres:/var/lib/postgresql/data:z
    environment:
      - POSTGRES_PASSWORD=pass
    expose:
      - "5432"
    ports:
      - "5432:5432"
