version: '2'

services:
  web4:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - postgres

  postgres:
    restart: always
    build: Postgresql
    volumes:
      - /Users/lukasz/docker_volumes/postgres:/var/lib/postgresql/data:z
    environment:
      - POSTGRES_PASSWORD=pass
    expose:
      - "5432"
    ports:
      - "5432:5432"
