"""Add header_image to Post model

Revision ID: 177a431886e8
Revises: b53e9fa0f167
Create Date: 2025-06-07 15:27:35.760034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '177a431886e8'
down_revision = 'b53e9fa0f167'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('header_image', sa.String(length=200), nullable=True))
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.drop_column('header_image')

    # ### end Alembic commands ###
